name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis-cluster:
        image: 'grokzen/redis-cluster:6.0.5'
        env:
           BIND_ADDRESS: '0.0.0.0'
           INITIAL_PORT: '9000'
        ports:
          - '9000-9005:9000-9005'
    strategy:
      matrix:
        perl:
          [
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install Valgrind
        run: sudo apt-get install -y valgrind
      - name: Install Minilla
        run: cpanm -n --with-recommends Minilla
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-configure .
      - name: Init submodules
        run: git submodule update --init
      - name: Run test
        run: minil test --author
        env:
          TEST_REDIS_CLUSTER_STARTUP_NODES: localhost:9000,localhost:9001,localhost:9002,localhost:9003,localhost:9004,localhost:9005

