name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis-cluster:
        image: 'grokzen/redis-cluster:6.0.5'
        env:
           BIND_ADDRESS: '0.0.0.0'
           INITIAL_PORT: '9000'
        ports:
          - '9000-9005:9000-9005'
    strategy:
      matrix:
        perl:
          [
            "5.40",
            "5.38",
            "5.30",
            "5.24",
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install Valgrind
        run: sudo apt-get install -y valgrind libevent-dev
      - name: Install Minilla
        run: cpanm -n --with-recommends Minilla
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-configure .
      - name: Init submodules
        run: git submodule update --init
      - name: Run test
        run: minil test --author --release
        env:
          TEST_REDIS_CLUSTER_STARTUP_NODES: 127.0.0.1:9000,127.0.0.1:9001,127.0.0.1:9002,127.0.0.1:9003,127.0.0.1:9004,127.0.0.1:9005

